### ISSUE TITLE
Completely black background in Nautilus when window is not focused

### ISSUE THREAD

**Issue by pellaeon** [wfpaisa/Plane-Gtk3#1]
Hi, first of all, great work on this theme, I like it a lot.
![ 2013-01-10 16:48:47](https://f.cloud.github.com/assets/916913/56081/e76ac07e-5b02-11e2-8921-5e7c6ff9d8c4.png)

As seen in the picture, Nautilus have completely black background when not focused.
This is Ubuntu 12.04

Thanks!

**Comment by wfpaisa** [comment]
Hi, I'm looking for a solution, because the problem comes from gtk-css styles generator templates ubuntu does not allow transparency in some widgets.
I hope to have an early by ubuntu team.

thank you very much for your comment, I'll be writing about possible solutions.

**Comment by wfpaisa** [comment]
solved ;)
